liip_imagine:
    driver: "gd"
    filter_sets:
        thumb_medium:
            filters:
                thumbnail:
                    size: [200, 200]
                    mode: outbound
                    allow_upscale: true
